# Generated by Django 5.2.6 on 2025-10-02 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rename_content_article_detailed_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_on',
            new_name='created_at',
        ),
    ]
