# Generated by Django 5.2.6 on 2025-10-05 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_comment_options_rename_body_comment_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
    ]
